# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
url: https://zhangtuodd.github.io
date_format: "ordinal"
title: zt博客
subtitle: "打码改变人生"
description: "Don't think too much,just do it."
keywords: ZT, ZT Blog, 张拓的博客, zhangtuodd,zhangtuo, 张拓, android, java
timezone: Asia/Beijing
encoding: "utf-8"
side_bar_repo_limit: 5

# ---------------- #
#      Author      #
# ---------------- #
author: Tuo zhang
organization: 
organization_url: 
github_username: zhangtuodd
location: Nanyang, China
email: zhangtuodd@163.com

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: 首页

  -
    href: /categories/
    label: 分类

#   -
#     href: /archives/
#     label: 归档

  -
    href: /wiki/
    label: 维基

  -
    href: /links/
    label: 链接

  -
    href: /about/
    label: 关于

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 10
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
gems:
    - jekyll-github-metadata
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
collections:
    wiki:
        output: true
        permalink: /wiki/:path/

repository: zhangtuodd

# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, gitment, gitalk
comments_provider: gitalk
# !!!重要!!! 请修改下面这些信息为你自己申请的
# !!!Important!!! Please modify infos below to yours
# https://disqus.com
disqus:
    username: 
# https://imsun.net/posts/gitment-introduction/
#gitment:
#    owner: mzlogin
#    repo: blog-comments
#    oauth:
#        client_id: d2e1cbbd298958076462
#        client_secret: b42a4178e5fd4a7cf63189ef4b1453b05c375709
# https://github.com/gitalk/gitalk#install
#gitalk:
#    owner: mzlogin
#    repo: blog-comments
#    clientID: d2e1cbbd298958076462
#    clientSecret: b42a4178e5fd4a7cf63189ef4b1453b05c375709
# Gitalk
gitalk:
  enable: true    #是否开启Gitalk评论
  clientID: 0e78fb193f116a6b0bf2                           #生成的clientID
  clientSecret: 8b7e57a9daeb8e99e683ddde52eda92b59b4974a    #生成的clientSecret
  repo: zhangtuodd.github.io    #仓库名称
  owner: zhangtuodd    #github用户名
  admin: zhangtuodd
  distractionFreeMode: true #是否启用类似FB的阴影遮罩
# 在使用其它评论组件时可点击显示 Disqus
lazy_load_disqus : false

# ---------------- #
#      Search      #
# ---------------- #
simple_jekyll_search:
    # 是否支持全文搜索
    fulltext: false
    # 最多显示多少条搜索结果
    limit: 10


# Analytics settings
# Baidu Analytics
ba_track_id: 2453886fd1f23f5385e27fe96300059e
